### ISSUE TITLE
native error:

### ISSUE THREAD

**Issue by fiorenzino** [quarkiverse/quarkiverse-minio#11]
In jvm docker image, the following code works fine:
```
public String uploadObject(String filename, InputStream inputStream, String mimeType) throws Exception {
        logger.info("uploadObject - bucketName:" + bucketName + ", filename: " + filename + ", mimeType: " + mimeType);
        try {
            minioClient.putObject(
                    PutObjectArgs.builder()
                            .bucket(bucketName)
                            .object(filename)
                            .stream(inputStream, -1, PART_SIZE)
                            .contentType(mimeType)
                            .build());
            return filename;
        } catch (Exception e) {
            throw new Exception("Failed uploading file [" + filename + "]", e);
        }
    }
```

In native mode, i receive that error:

```
  Caused by: java.lang.RuntimeException: class io.minio.PutObjectArgs must have no argument constructor
     at io.minio.BaseArgs$Builder.newInstance(BaseArgs.java:135)
     at io.minio.BaseArgs$Builder.build(BaseArgs.java:148)
     at it.ictgroup.portali.messages.service.S3Client.uploadObject(S3Client.java:38)
     ... 45 more
```

Have you some hacking to UPLOAD file (using InputStream) in native mode?

best regards

**Comment by fiorenzino** [comment]
In jvm image, the following cod works fine:    

`
public String uploadObject(String filename, InputStream inputStream, String mimeType) throws Exception {
        logger.info("uploadObject - bucketName:" + bucketName + ", filename: " + filename + ", mimeType: " + mimeType);
        try {
            minioClient.putObject(
                    PutObjectArgs.builder()
                            .bucket(bucketName)
                            .object(filename)
                            .stream(inputStream, -1, PART_SIZE)
                            .contentType(mimeType)
                            .build());
            return filename;
        } catch (Exception e) {
            throw new Exception("Failed uploading file [" + filename + "]", e);
        }
    }
`
In native mode, i receive that error:

`
Caused by: java.lang.RuntimeException: class io.minio.PutObjectArgs must have no argument constructor
at io.minio.BaseArgs$Builder.newInstance(BaseArgs.java:135)
at io.minio.BaseArgs$Builder.build(BaseArgs.java:148)
at it.ictgroup.portali.messages.service.S3Client.uploadObject(S3Client.java:38)
`
Have you some hacking to UPLOAD file (using InputStream) in native mode?

**Comment by jtama-op** [comment]
Hi,
Which version are you using ?

**Comment by fiorenzino** [comment]
Hi,

quarkus version:

`<quarkus.platform.version>1.9.2.Final</quarkus.platform.version>
`

quarkiverse.minio:
```
  <dependency>
            <groupId>io.quarkiverse.minio</groupId>
            <artifactId>minio-client</artifactId>
            <version>0.0.1</version>
        </dependency>
```

**Comment by jtama-op** [comment]
Just up minio extension version to 0.1.0. That should solve you issue.

**Comment by fiorenzino** [comment]
ok, i will try today!

**Comment by fiorenzino** [comment]
YES, the upgrade solved the problem!

perfect!
